/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
	{
		_id: 'O-w-NKMowIY',
		title: 'Valorant Skin Challenge | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Challenges',
	},
	{
		_id: 'ltinSvVJbUw',
		title: 'POKEMON + MINECRAFT = TOO MUCH FUN | ZOEF GAMES',
		creator: 'Zoef Games',
		categoryName: 'Gameplays',
	},
	{
		_id: '-R58pnOyuvc',
		title: '200 IQ hide and seek Among us w/GaurgeX | stream Highlight',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'RcO2bNGOvFA',
		title: 'Funny Moments from Among us | Twitch Highlight | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'O-w-NKMowIY',
		title: 'Valorant Skin Challenge | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Challenges',
	},
	{
		_id: 'ltinSvVJbUw',
		title: 'POKEMON + MINECRAFT = TOO MUCH FUN | ZOEF GAMES',
		creator: 'Zoef Games',
		categoryName: 'Gameplays',
	},
	{
		_id: '-R58pnOyuvc',
		title: '200 IQ hide and seek Among us w/GaurgeX | stream Highlight',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'RcO2bNGOvFA',
		title: 'Funny Moments from Among us | Twitch Highlight | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'O-w-NKMowIY',
		title: 'Valorant Skin Challenge | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Challenges',
	},
	{
		_id: 'ltinSvVJbUw',
		title: 'POKEMON + MINECRAFT = TOO MUCH FUN | ZOEF GAMES',
		creator: 'Zoef Games',
		categoryName: 'Gameplays',
	},
	{
		_id: '-R58pnOyuvc',
		title: '200 IQ hide and seek Among us w/GaurgeX | stream Highlight',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'RcO2bNGOvFA',
		title: 'Funny Moments from Among us | Twitch Highlight | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'O-w-NKMowIY',
		title: 'Valorant Skin Challenge | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Challenges',
	},
	{
		_id: 'ltinSvVJbUw',
		title: 'POKEMON + MINECRAFT = TOO MUCH FUN | ZOEF GAMES',
		creator: 'Zoef Games',
		categoryName: 'Gameplays',
	},
	{
		_id: '-R58pnOyuvc',
		title: '200 IQ hide and seek Among us w/GaurgeX | stream Highlight',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'RcO2bNGOvFA',
		title: 'Funny Moments from Among us | Twitch Highlight | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'O-w-NKMowIY',
		title: 'Valorant Skin Challenge | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Challenges',
	},
	{
		_id: 'ltinSvVJbUw',
		title: 'POKEMON + MINECRAFT = TOO MUCH FUN | ZOEF GAMES',
		creator: 'Zoef Games',
		categoryName: 'Gameplays',
	},
	{
		_id: '-R58pnOyuvc',
		title: '200 IQ hide and seek Among us w/GaurgeX | stream Highlight',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'RcO2bNGOvFA',
		title: 'Funny Moments from Among us | Twitch Highlight | Zoef Games',
		creator: 'Zoef Games',
		categoryName: 'Gameplay',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
	{
		_id: 'SzuoB4_RpT4',
		title: "Marvel's Avengers Review(*NO SPOLIERS*)",
		creator: 'Zoef Games',
		categoryName: 'Podcast',
	},
];
